version: "3.9"

services:
  bbdd:
    image: mysql:5.7.35
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    ports:
      - ${FILEBOX_BBDD_PORT:-3306}:3306
 
    expose:
      - 33060
      - 3306
    volumes:
      - ${FILEBOX_DIR}/filebox/ddbb/:/var/lib/mysql
    networks:
      - default

  server:
    depends_on:
      - bbdd
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - ${FILEBOX_SERVER_PORT:-3001}:3001
    expose:
      - 3001
    networks:
      - default
    environment:
      - TEMPORAL_FILES=/home/node/app/temporalfiles/
      - MEMORY_FILES=/home/node/app/memory/
      - HOST_DDBB=bbdd
    volumes:
      - ${FILEBOX_DIR}/filebox/memory/:/home/node/app/memory/

  web:
    depends_on:
      - server
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    ports:
      - ${FILEBOX_WEB_PORT:-3000}:3000
    expose:
      - 3000
    networks:
      - default
    environment:
      - NEXT_PUBLIC_API_SERVER_URL=${SERVER_URL:-127.0.0.1}
      - NEXT_PUBLIC_API_SERVER_PORT=3001
    
  


    
    


    

